INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1040108', 'lIGHT - 350 ML - MANGA', 'LATA', '350 ML', 'MANGA', 4.56);

INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1040108', 'CLEAN - 350 ML - LARANJA', 'LATA', '350 ML', 'LARANJA', 10.56);

INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1040208', 'CLEAN - 1.5 LITROS - MELANCIA', 'GARRAFA', '1.5 LITROS', 'MELANCIA', 17.56);

SELECT * FROM TB_PRODUTOS;


