DROP TABLE TABELA_DE_VENDEDORES2;

CREATE TABLE TB_VENDEDORES (
     MATRICULA varchar(5),
     NOME varchar(100),
     PERCENTUAL_COMISSAO float
);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00233', 'JOSÉ GERALDO DA FONSECA', 10.0);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00235', 'MÁRCIO ALMEIDA SILVA', 8.0);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00236', 'CLÁUDIA MORAIS', 8.0);

SELECT * FROM TB_VENDEDORES;

UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 11.0
WHERE MATRICULA = '00236';

UPDATE TB_VENDEDORES SET NOME = 'JOSÉ GERALDO DA FONSECA JUNIOR'
WHERE MATRICULA = '00233';

ALTER TABLE TB_VENDEDORES ADD CONSTRAINT PK_TB_VENDEDORES PRIMARY KEY (MATRICULA);

ALTER TABLE TB_VENDEDORES ADD DATA_ADMISSAO DATE;

ALTER TABLE TB_VENDEDORES ADD DE_FERIAS VARCHAR(3);

SELECT * FROM TB_VENDEDORES;

UPDATE TB_VENDEDORES SET DATA_ADMISSAO = TO_DATE('10/12/2016', 'DD/MM/YYYY'), DE_FERIAS = 'NAO'
WHERE MATRICULA = '00233';

UPDATE TB_VENDEDORES SET DATA_ADMISSAO = TO_DATE('10/12/2018', 'DD/MM/YYYY'), DE_FERIAS = 'SIM'
WHERE MATRICULA = '00235';

UPDATE TB_VENDEDORES SET DATA_ADMISSAO = TO_DATE('10/12/2018', 'DD/MM/YYYY'), DE_FERIAS = 'NAO'
WHERE MATRICULA = '00236';





























