SELECT * FROM TB_VENDEDORES WHERE PERCENTUAL_COMISSAO >= 0.10;

SELECT * FROM TB_VENDEDORES WHERE TO_CHAR(DATA_ADMISSAO, 'YYYY') > 2016;

SELECT * FROM TB_VENDEDORES WHERE DE_FERIAS = 1 AND TO_CHAR(DATA_ADMISSAO, 'YYYY') > 2016;